name: Template Check

on:
  push:
    branches:
      - main

jobs:
  changed_files:
    runs-on: windows-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        # NOTE: `since_last_remote_commit: true` is implied by default and falls back to the previous local commit.

      - name: List all changed files
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        shell: pwsh
        run: |
          if ($env:ALL_CHANGED_FILES.Contains("Script Blocks\Template_v2.js")) {
            Write-Host "The template was changed"
            # create an update issue for scanner config files
            gh issue create --title "Update Configurations to match template" --project "Scanner Configuration To-Do" --assignee "masonritchason" --label "enhancement" --body "The template has been changed. Please update Scanner Configurations to match the changes and upload the modified scripts to the appropriate scanners."
          } else {
            Write-Host "The template was not changed"
          }