name: Template Check

on:
  push:
    branches:
      - main

env: SCANNER_CONFIG_FILES = [Production\Deburr\Deburr.js, Production\Production Control\PCReceiving.js, Production\Production Control\PCStocking.js, Production\Steel\Civic Assembly\CivicAssembly.js, Production\Steel\Civic Pivot Housing MC\PivotHousingMC.js, Production\Steel\Civic Shaft Clinch\CivicShaftClinch.js]

jobs:
  changed_files:
    runs-on: windows-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        # NOTE: `since_last_remote_commit: true` is implied by default and falls back to the previous local commit.

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        shell: pwsh
        run: |
          if ($env:ALL_CHANGED_FILES -contains "Script Blocks\Template_v2.js") {
            Write-Host "The template was changed"
            # create an update issue for each scanner config file
            foreach ($configuration in $env:SCANNER_CONFIG_FILES) {
              # create an issue
              gh issue create --title "Update $file to match template" --project "Scanner Configuration To-Do" --assignee "masonritchason" --label "enhancement" --body "The template has been changed. Please update this file to match the changes and upload the modified script to the appropriate scanner(s)."
            }
          } else {
            Write-Host "The template was not changed"
          }